version: '3.7'

volumes:
  postgres_data:
  static_value:
  media_value:
services:
  db:
    image: postgres:12.4
    restart: always
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
       - static_value:/code/static
       - media_value:/code/media
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.9
    ports:
    - "80:80"
    volumes:
#    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - "./nginx/templates:/etc/nginx/templates"
    - static_value:/var/html/static/
    - media_value:/var/html/media/
    env_file:
      - ./.env
    command: /bin/bash -c "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf"
    depends_on:
      - web
